typedef enum {
    INLA_CGENERIC_VOID = 0,
    INLA_CGENERIC_Q,
    INLA_CGENERIC_GRAPH,
    INLA_CGENERIC_MU,
    INLA_CGENERIC_INITIAL,
    INLA_CGENERIC_LOG_NORM_CONST,
    INLA_CGENERIC_LOG_PRIOR,
    INLA_CGENERIC_QUIT
} inla_cgeneric_cmd_tp;

