// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_mu_ar1
void compute_mu_ar1(NumericVector mu, int n, NumericVector tforcing, NumericVector phis);
RcppExport SEXP _INLA_ews_compute_mu_ar1(SEXP muSEXP, SEXP nSEXP, SEXP tforcingSEXP, SEXP phisSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tforcing(tforcingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type phis(phisSEXP);
    compute_mu_ar1(mu, n, tforcing, phis);
    return R_NilValue;
END_RCPP
}
// compute_mu_fgn
void compute_mu_fgn(NumericVector mu, int n, NumericVector tforcing, NumericVector Hs);
RcppExport SEXP _INLA_ews_compute_mu_fgn(SEXP muSEXP, SEXP nSEXP, SEXP tforcingSEXP, SEXP HsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tforcing(tforcingSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Hs(HsSEXP);
    compute_mu_fgn(mu, n, tforcing, Hs);
    return R_NilValue;
END_RCPP
}
// timesTwo
int timesTwo(int x);
RcppExport SEXP _INLA_ews_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_INLA_ews_compute_mu_ar1", (DL_FUNC) &_INLA_ews_compute_mu_ar1, 4},
    {"_INLA_ews_compute_mu_fgn", (DL_FUNC) &_INLA_ews_compute_mu_fgn, 4},
    {"_INLA_ews_timesTwo", (DL_FUNC) &_INLA_ews_timesTwo, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_INLA_ews(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
