# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute mu in C for AR(1) model
#' 
#' Void function that gives the forced response for the AR(1) model with 
#' time-dependent memory in C.
#' 
#' @param mu Vector that will be overwritten with the forced response.
#' @param n Integer denoting the dimension of \code{mu}.
#' @param tforcing Vector with the shifted and scaled known forcing.
#' @param phis Vector describing the time-dependent lag-one correlation.
#' 
#' @author Eirik Myrvoll-Nilsen, \email{eirikmn91@gmail.com}
#' @seealso \code{\link{mu.computer}}
#' @keywords C ar1 forcing
#' @export
compute_mu_ar1 <- function(mu, n, tforcing, phis) {
    invisible(.Call(`_INLA_ews_compute_mu_ar1`, mu, n, tforcing, phis))
}

#' Compute mu in C for fGn model
#' 
#' Void function that gives the forced response for the fractional Gaussian noise 
#' model with time-dependent memory in C.
#' 
#' @param mu Vector that will be overwritten with the forced response.
#' @param n Integer denoting the dimension of \code{mu}.
#' @param tforcing Vector with the shifted and scaled known forcing.
#' @param Hs Vector describing the time-dependent Hurst exponent.
#' 
#' @author Eirik Myrvoll-Nilsen, \email{eirikmn91@gmail.com}
#' @seealso \code{\link{mu.computer}}
#' @keywords C fgn forcing
#' @export
compute_mu_fgn <- function(mu, n, tforcing, Hs) {
    invisible(.Call(`_INLA_ews_compute_mu_fgn`, mu, n, tforcing, Hs))
}

#' Multiply a number by two
#' 
#' @param x A single integer.
#' @export
timesTwo <- function(x) {
    .Call(`_INLA_ews_timesTwo`, x)
}

