# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute mu in C for AR(1) model
#' 
#' Void function that gives the forced response for the AR(1) model with 
#' time-dependent memory in C.
#' 
#' @param means Vector that will be overwritten with the forced response.
#' @param z Vector with the shifted and scaled known forcing.
#' @param n Integer denoting the dimension of \code{mu}.
#' @param lambda Vector describing the lambdas at each sampled time step.
#' @param time Vector describing the time steps.
#' 
#' @author Eirik Myrvoll-Nilsen, \email{eirikmn91@gmail.com}
#' @seealso \code{\link{mucomputer}}
#' @keywords C ar1 forcing
#' @export
c_mu_ar1 <- function(means, z, n, lambda, time) {
    invisible(.Call(`_INLA_ews_c_mu_ar1`, means, z, n, lambda, time))
}

